name: Solar System Workflow

on:
    workflow_dispatch:    #to run manually from the Actions tab
    push:
        branches:
            - main
            - 'feature/*'    #to run on push to any feature branch

env:
    MONGO_URI: mongodb+srv://supercluster.d83jj.mongodb.net/superData   #to provide mongodb URI
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}    #to store MongoDB username in repo variables
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}    #to securely store MongoDB password

jobs:
    unit-testing:
        runs-on: ${{matrix.os}}    #to run the job on the latest version of Ubuntu
        name: Unit Testing
        strategy:
            matrix:
                node-version: [18,24]    #to specify the Node.js version for testing
                os: [ubuntu-latest, macos-latest]    #to specify the operating systems for testing
                exclude:
                    - node-version: 18
                      os: macos-latest    #to exclude Node.js 18 on macOS due to compatibility issues
        steps:
            - name: Checkout code
              uses: actions/checkout@v4    #to check out the code from the repository

            - name: Set up Node.js
              uses: actions/setup-node@v3    #to set up Node.js environment
              with:
                  node-version: ${{matrix.node-version}}    #specify the version of Node.js to use

            - name: Install dependencies
              run: npm install    #to install the project dependencies

            - name: Run unit tests
              run: npm test    #to run the unit tests defined in the project

            - name: Archieve test results
              if: always()
              uses: actions/upload-artifact@v7    #to upload test results as an artifact
              with:
                  name: test-results
                  path: test-results.xml    #specify the path to the test results directory



    code-coverage:
        runs-on: ubuntu-latest    #to run the job on the latest version of Ubuntu
        name: Code Coverage
        steps:
            - name: Checkout code
              uses: actions/checkout@v4    #to check out the code from the repository

            - name: Set up Node.js
              uses: actions/setup-node@v3    #to set up Node.js environment
              with:
                  node-version: ${{matrix.node-version}}    #specify the version of Node.js to use

            - name: Install dependencies
              run: npm install    #to install the project dependencies

            - name: Check code coverage
              continue-on-error: true    #to allow the workflow to continue even if the code coverage command fails
              run: npm run coverage    #to run the code coverage command defined in the project

            - name: Upload code coverage report
              uses: actions/upload-artifact@v7    #to upload code coverage report as an artifact
              with:
                  name: code-coverage-report
                  path: coverage       #specify the path to the code coverage report directory
                  retention-days: 5    #specify the number of days to retain the artifact
